[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend build complete - no build step needed'"]

[start]
cmd = "node server.js"
